include colors/gruvbox-material-dark-medium.conf

map ctrl+c  copy_to_clipboard
map ctrl+v  paste_from_clipboard
map ctrl+shift+c send_text all \x03

background_opacity 0.9

window_margin_width 0
window_padding_width 0 2